In [20]:
%tsql SHOW SCHEMAS FROM iceberg;

               Schema
0             default
1  information_schema
2             nyc_gov
3              system
4                test

In [21]:
%tsql  --max-colwidth 200 SHOW CREATE SCHEMA iceberg.nyc_gov;

                                                                                                                   Create Schema
0  CREATE SCHEMA iceberg.nyc_gov\nAUTHORIZATION USER "trino-client"\nWITH (\n   location = 's3a://trino-lakehouse/nyc_gov.db'\n)

In [22]:
%s3 ls s3://trino-lakehouse/nyc_gov.db/

                           PRE country_codes-9a177fe4c3ba4674ba94c599d18f2dee/
                           PRE given_name_frequency-5ff20512f56e4490afaebd20cadceae0/
                           PRE name_equivalence-3802ce524d854adab957ac4f027e7998/
                           PRE popular_names_by_country_2026-d2189a769d4c4a1fb70e0dd01fe31da5/
                           PRE surname_frequency-1d0faf92bf7d41eba5ae3eb05a594d57/
2026-09-09 14:54:27          0

In [25]:
%%tsql
SELECT table_catalog, table_schema, table_name, table_type
FROM iceberg.information_schema.tables
WHERE table_catalog ='iceberg'
ORDER BY table_schema, table_name;

,table_catalog,table_schema,table_name,table_type
0,iceberg,information_schema,applicable_roles,BASE TABLE
1,iceberg,information_schema,columns,BASE TABLE
2,iceberg,information_schema,enabled_roles,BASE TABLE
3,iceberg,information_schema,roles,BASE TABLE
4,iceberg,information_schema,schemata,BASE TABLE
5,iceberg,information_schema,table_privileges,BASE TABLE
6,iceberg,information_schema,tables,BASE TABLE
7,iceberg,information_schema,views,BASE TABLE
8,iceberg,nyc_gov,country_codes,BASE TABLE
9,iceberg,nyc_gov,given_name_frequency,BASE TABLE
10,iceberg,nyc_gov,name_equivalence,BASE TABLE
11,iceberg,nyc_gov,popular_names_by_country_2026,BASE TABLE
12,iceberg,nyc_gov,surname_frequency,BASE TABLE
13,iceberg,system,iceberg_tables,BASE TABLE
14,iceberg,test,my_table,BASE TABLE

In [24]:
%%tsql
SELECT *
FROM iceberg.nyc_gov.country_codes
LIMIT 3

  country_code country_name
0  Afghanistan           AF
1      Albania           AL
2      Algeria           DZ