In [10]:
import boto3
import pandas as pd
from botocore.config import Config

S3_ENDPOINT = 'https://rustfs:9000'
S3_REGION = 'us-east-1'
S3_CA_BUNDLE = '/etc/rustfs/tls/ca.crt'

s3 = boto3.client(
    's3',
    endpoint_url=S3_ENDPOINT,
    aws_access_key_id='admin',
    aws_secret_access_key='secret2',
    region_name=S3_REGION,
    verify=S3_CA_BUNDLE,
    config=Config(s3={'addressing_style': 'path'}),
)

In [11]:
bucket_response = s3.list_buckets()

buckets = pd.DataFrame(
    [
        {
            'Name': bucket['Name'],
            'CreationDate': bucket['CreationDate'],
        }
        for bucket in bucket_response.get('Buckets', [])
    ],
    columns=['Name', 'CreationDate'],
)

display(buckets)

              Name                     CreationDate
0  delta-lakehouse 2026-09-30 13:46:04.250000+00:00
1        my-bucket 2026-09-30 13:47:03.092000+00:00
2  trino-lakehouse 2026-09-30 13:46:03.355000+00:00

In [12]:
bucket_name = 'trino-lakehouse'
objects = []

for page in s3.get_paginator('list_objects_v2').paginate(Bucket=bucket_name):
    objects.extend(
        {
            'Key': item['Key'],
            'Size': item['Size'],
            'LastModified': item['LastModified'],
        }
        for item in page.get('Contents', [])
    )

bucket_objects = pd.DataFrame(
    objects,
    columns=['Key', 'Size', 'LastModified'],
).sort_values('Key', ignore_index=True)

display(bucket_objects)

Empty DataFrame
Columns: [Key, Size, LastModified]
Index: []