In [1]:
from squid.resources.s3 import get_s3

In [2]:
s3 = get_s3()
s3

In [3]:
import boto3
import pandas as pd
bucket_response = s3.list_buckets()

buckets = pd.DataFrame(
    [
        {
            'Name': bucket['Name'],
            'CreationDate': bucket['CreationDate'],
        }
        for bucket in bucket_response.get('Buckets', [])
    ],
    columns=['Name', 'CreationDate'],
)

display(buckets)

              Name                     CreationDate
0  delta-lakehouse 2026-09-30 13:46:04.250000+00:00
1        my-bucket 2026-09-30 13:47:03.092000+00:00
2  trino-lakehouse 2026-09-30 13:46:03.355000+00:00

In [4]:
if buckets.empty:
    print("No buckets available.")
else:
    sample_bucket = buckets.iloc[0]["Name"]
    object_response = s3.list_objects_v2(Bucket=sample_bucket, MaxKeys=10)
    objects = pd.DataFrame(
        [
            {
                "Key": item["Key"],
                "Size": item["Size"],
                "LastModified": item["LastModified"],
            }
            for item in object_response.get("Contents", [])
        ],
        columns=["Key", "Size", "LastModified"],
    )
    print(f"First {len(objects)} object(s) in s3://{sample_bucket}:")
    display(objects)

First 0 object(s) in s3://delta-lakehouse:

Empty DataFrame
Columns: [Key, Size, LastModified]
Index: []