In [1]:
import pandas as pd
from squid.resources.trino import get_trino
from squid.jupyter.extensions import viewdf, viewdf_pandas

In [2]:
conn = get_trino()
cursor = conn.cursor()

In [3]:
def tsql(query: str):
    cursor.execute(query)
    columns = [column[0] for column in cursor.description]
    iceberg_system_tables = pd.DataFrame(cursor.fetchall(), columns=columns)
    display(iceberg_system_tables)

In [4]:
query = """
SELECT *
FROM iceberg.system.iceberg_tables
"""

tsql(query)

  table_schema                     table_name
0      nyc_gov  popular_names_by_country_2026
1      nyc_gov               name_equivalence
2      nyc_gov                  country_codes
3      nyc_gov           given_name_frequency
4      nyc_gov              surname_frequency
5         test                       my_table

In [5]:
query = """
SELECT table_catalog, table_schema, table_name, table_type
FROM iceberg.information_schema.tables
ORDER BY table_schema, table_name
"""

tsql(query)

,table_catalog,table_schema,table_name,table_type
0,iceberg,information_schema,applicable_roles,BASE TABLE
1,iceberg,information_schema,columns,BASE TABLE
2,iceberg,information_schema,enabled_roles,BASE TABLE
3,iceberg,information_schema,roles,BASE TABLE
4,iceberg,information_schema,schemata,BASE TABLE
5,iceberg,information_schema,table_privileges,BASE TABLE
6,iceberg,information_schema,tables,BASE TABLE
7,iceberg,information_schema,views,BASE TABLE
8,iceberg,nyc_gov,country_codes,BASE TABLE
9,iceberg,nyc_gov,given_name_frequency,BASE TABLE
10,iceberg,nyc_gov,name_equivalence,BASE TABLE
11,iceberg,nyc_gov,popular_names_by_country_2026,BASE TABLE
12,iceberg,nyc_gov,surname_frequency,BASE TABLE
13,iceberg,system,iceberg_tables,BASE TABLE
14,iceberg,test,my_table,BASE TABLE

In [6]:
cursor.execute("""
CREATE SCHEMA IF NOT EXISTS iceberg.test
""")

In [7]:
cursor.execute("""
DROP TABLE IF EXISTS iceberg.test.my_table
""")

In [8]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS iceberg.test.my_table (
    id BIGINT,
    name VARCHAR,
    amount DOUBLE,
    created_at TIMESTAMP
)
""")

In [9]:
query = """
SELECT *
FROM iceberg.system.iceberg_tables
"""

tsql(query)

  table_schema                     table_name
0      nyc_gov  popular_names_by_country_2026
1      nyc_gov               name_equivalence
2      nyc_gov                  country_codes
3      nyc_gov           given_name_frequency
4      nyc_gov              surname_frequency
5         test                       my_table

In [10]:
cursor.execute("""
INSERT INTO iceberg.test.my_table
VALUES
    (1, 'Alice', 100.5, CURRENT_TIMESTAMP),
    (2, 'Bob',   200.0, CURRENT_TIMESTAMP)
""")

In [11]:
query = """
SELECT *
FROM iceberg.test.my_table
"""
tsql(query)

   id   name  amount              created_at
0   1  Alice   100.5 2026-09-17 19:39:09.493
1   2    Bob   200.0 2026-09-17 19:39:09.493