In [10]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [18]:
%reload_ext autoreload
%autoreload 2
import squid 
from squid.resources.trino import get_trino
import pandas as pd
from squid.jupyter.extensions import viewdf, viewdf_pandas

In [12]:
conn = get_trino()
conn

In [13]:
cursor = conn.cursor()
cursor

In [14]:
cursor.execute("SELECT version()")
rows = cursor.fetchall()
display(rows)

[['483']]

In [15]:
cursor.execute("SELECT * FROM system.runtime.queries")
rows = cursor.fetchall()
display(rows)

[['20260914_113805_00005_42crw',
  'FINISHED',
  'trino-client',
  'trino-python-client',
  'SELECT version()',
  ['global'],
  0,
  1,
  3,
  datetime.datetime(2026, 9, 14, 11, 38, 5, 634000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 38, 5, 635000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 38, 5, 650000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 38, 5, 648000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  None,
  None],
 ['20260914_113800_00004_42crw',
  'FINISHED',
  'trino-client',
  'trino-python-client',
  '\nSELECT *\nFROM iceberg.system.iceberg_tables\n',
  ['global'],
  0,
  1,
  3,
  datetime.datetime(2026, 9, 14, 11, 38, 0, 192000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 38, 0, 193000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 38, 0, 214000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 38, 0, 342000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  None,
  None],
 ['20260914_113722_00002_42crw',
  'FINISHED',
  'trino-client',
  'trino-python-client',
  '\nSELECT *\nFROM iceberg.system.iceberg_tables\n',
  ['global'],
  0,
  14,
  4,
  datetime.datetime(2026, 9, 14, 11, 37, 22, 960000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 37, 22, 975000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 37, 23, 54000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 37, 23, 53000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  None,
  None],
 ['20260914_113728_00003_42crw',
  'FINISHED',
  'trino-client',
  'trino-python-client',
  '\nSELECT table_catalog, table_schema, table_name, table_type\nFROM iceberg.information_schema.tables\nORDER BY table_schema, table_name\n',
  ['global'],
  0,
  4,
  15,
  datetime.datetime(2026, 9, 14, 11, 37, 28, 597000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 37, 28, 602000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 37, 28, 679000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 37, 28, 673000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  None,
  None],
 ['20260914_113657_00001_42crw',
  'FINISHED',
  'trino-client',
  'trino-python-client',
  'SELECT * FROM system.runtime.queries',
  ['global'],
  0,
  7,
  12,
  datetime.datetime(2026, 9, 14, 11, 36, 57, 634000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 36, 57, 641000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 36, 57, 698000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 36, 57, 695000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  None,
  None],
 ['20260914_113656_00000_42crw',
  'FINISHED',
  'trino-client',
  'trino-python-client',
  'SELECT version()',
  ['global'],
  4,
  28,
  88,
  datetime.datetime(2026, 9, 14, 11, 36, 56, 664000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 36, 56, 696000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 36, 56, 940000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 36, 56, 924000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  None,
  None],
 ['20260914_113805_00006_42crw',
  'RUNNING',
  'trino-client',
  'trino-python-client',
  'SELECT * FROM system.runtime.queries',
  ['global'],
  0,
  2,
  5,
  datetime.datetime(2026, 9, 14, 11, 38, 5, 979000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 38, 5, 981000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  datetime.datetime(2026, 9, 14, 11, 38, 5, 988000, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  None,
  None,
  None]]

In [19]:
def tsql(query: str):
    cursor.execute(query)
    columns = [column[0] for column in cursor.description]
    iceberg_system_tables = pd.DataFrame(cursor.fetchall(), columns=columns)
    display(iceberg_system_tables)

In [20]:
query = """
SELECT *
FROM iceberg.system.iceberg_tables
"""

tsql(query)

  table_schema                     table_name
0      nyc_gov  popular_names_by_country_2026
1      nyc_gov               name_equivalence
2      nyc_gov                  country_codes
3      nyc_gov           given_name_frequency
4      nyc_gov              surname_frequency
5         test                       my_table

In [21]:
query = """
SELECT table_catalog, table_schema, table_name, table_type
FROM iceberg.information_schema.tables
ORDER BY table_schema, table_name
"""

tsql(query)

,table_catalog,table_schema,table_name,table_type
0,iceberg,information_schema,applicable_roles,BASE TABLE
1,iceberg,information_schema,columns,BASE TABLE
2,iceberg,information_schema,enabled_roles,BASE TABLE
3,iceberg,information_schema,roles,BASE TABLE
4,iceberg,information_schema,schemata,BASE TABLE
5,iceberg,information_schema,table_privileges,BASE TABLE
6,iceberg,information_schema,tables,BASE TABLE
7,iceberg,information_schema,views,BASE TABLE
8,iceberg,nyc_gov,country_codes,BASE TABLE
9,iceberg,nyc_gov,given_name_frequency,BASE TABLE
10,iceberg,nyc_gov,name_equivalence,BASE TABLE
11,iceberg,nyc_gov,popular_names_by_country_2026,BASE TABLE
12,iceberg,nyc_gov,surname_frequency,BASE TABLE
13,iceberg,system,iceberg_tables,BASE TABLE
14,iceberg,test,my_table,BASE TABLE

In [7]:
conn.close()
cursor.close()