In [7]:
%tsql SELECT version()

  _col0
0   483

In [8]:
%tsql SELECT * FROM system.runtime.queries

,query_id,state,user,source,query,resource_group_id,queued_time_ms,analysis_time_ms,planning_time_ms,created,started,last_heartbeat,end,error_type,error_code
0,20260916_164444_00001_9kwgp,FINISHED,trino-client,trino-python-client,SELECT * FROM system.runtime.queries,[global],0,7,12,2026-09-16 16:44:44.234000+00:00,2026-09-16 16:44:44.242000+00:00,2026-09-16 16:44:44.308000+00:00,2026-09-16 16:44:44.308000+00:00,None,None
1,20260916_164618_00007_9kwgp,FINISHED,trino-client,trino-python-client,SHOW SCHEMAS FROM delta,[global],0,11,3,2026-09-16 16:46:18.325000+00:00,2026-09-16 16:46:18.336000+00:00,2026-09-16 16:46:18.379000+00:00,2026-09-16 16:46:18.379000+00:00,None,None
2,20260916_164446_00002_9kwgp,FINISHED,trino-client,trino-python-client,SELECT *\nFROM iceberg.system.iceberg_tables,[global],0,12,3,2026-09-16 16:44:46.490000+00:00,2026-09-16 16:44:46.503000+00:00,2026-09-16 16:44:46.568000+00:00,2026-09-16 16:44:46.566000+00:00,None,None
3,20260916_164448_00003_9kwgp,FINISHED,trino-client,trino-python-client,"SELECT table_catalog, table_schema, table_name...",[global],0,2,15,2026-09-16 16:44:48.007000+00:00,2026-09-16 16:44:48.009000+00:00,2026-09-16 16:44:48.079000+00:00,2026-09-16 16:44:48.071000+00:00,None,None
4,20260916_164556_00005_9kwgp,FINISHED,trino-client,trino-python-client,SHOW CATALOGS,[global],0,1,4,2026-09-16 16:45:56.489000+00:00,2026-09-16 16:45:56.490000+00:00,2026-09-16 16:45:56.512000+00:00,2026-09-16 16:45:56.510000+00:00,None,None
5,20260916_164441_00000_9kwgp,FINISHED,trino-client,trino-python-client,SELECT version(),[global],4,30,80,2026-09-16 16:44:41.533000+00:00,2026-09-16 16:44:41.567000+00:00,2026-09-16 16:44:41.821000+00:00,2026-09-16 16:44:41.807000+00:00,None,None
6,20260916_175738_00011_9kwgp,RUNNING,trino-client,trino-python-client,SELECT * FROM system.runtime.queries,[global],0,3,5,2026-09-16 17:57:38.985000+00:00,2026-09-16 17:57:38.988000+00:00,2026-09-16 17:57:38.994000+00:00,NaT,None,None
7,20260916_164611_00006_9kwgp,FINISHED,trino-client,trino-python-client,SHOW SCHEMAS FROM iceberg,[global],0,1,8,2026-09-16 16:46:11.810000+00:00,2026-09-16 16:46:11.812000+00:00,2026-09-16 16:46:11.841000+00:00,2026-09-16 16:46:11.840000+00:00,None,None
8,20260916_164625_00008_9kwgp,FINISHED,trino-client,trino-python-client,SHOW SCHEMAS FROM system,[global],0,1,7,2026-09-16 16:46:25.344000+00:00,2026-09-16 16:46:25.345000+00:00,2026-09-16 16:46:25.368000+00:00,2026-09-16 16:46:25.368000+00:00,None,None
9,20260916_164536_00004_9kwgp,FINISHED,trino-client,trino-python-client,SHOW CATALOGS,[global],0,2,92,2026-09-16 16:45:36.460000+00:00,2026-09-16 16:45:36.462000+00:00,2026-09-16 16:45:36.576000+00:00,2026-09-16 16:45:36.574000+00:00,None,None
10,20260916_173219_00009_9kwgp,FINISHED,trino-client,trino-python-client,SELECT * FROM system.runtime.queries,[global],1,3,6,2026-09-16 17:32:19.524000+00:00,2026-09-16 17:32:19.527000+00:00,2026-09-16 17:32:19.544000+00:00,2026-09-16 17:32:19.544000+00:00,None,None
11,20260916_175737_00010_9kwgp,FINISHED,trino-client,trino-python-client,SELECT version(),[global],0,1,5,2026-09-16 17:57:37.711000+00:00,2026-09-16 17:57:37.713000+00:00,2026-09-16 17:57:37.725000+00:00,2026-09-16 17:57:37.724000+00:00,None,None

In [9]:
%%tsql
SELECT *
FROM iceberg.system.iceberg_tables

Empty DataFrame
Columns: [table_schema, table_name]
Index: []

In [10]:
%%tsql
SELECT table_catalog, table_schema, table_name, table_type
FROM iceberg.information_schema.tables
ORDER BY table_schema, table_name

  table_catalog        table_schema        table_name  table_type
0       iceberg  information_schema  applicable_roles  BASE TABLE
1       iceberg  information_schema           columns  BASE TABLE
2       iceberg  information_schema     enabled_roles  BASE TABLE
3       iceberg  information_schema             roles  BASE TABLE
4       iceberg  information_schema          schemata  BASE TABLE
5       iceberg  information_schema  table_privileges  BASE TABLE
6       iceberg  information_schema            tables  BASE TABLE
7       iceberg  information_schema             views  BASE TABLE
8       iceberg              system    iceberg_tables  BASE TABLE

In [11]:
%tsql SHOW CATALOGS;

   Catalog
0    delta
1  iceberg
2   system