In [5]:
%tsql SELECT version()

  _col0
0   483

In [6]:
%tsql SELECT * FROM system.runtime.queries

,query_id,state,user,source,query,resource_group_id,queued_time_ms,analysis_time_ms,planning_time_ms,created,started,last_heartbeat,end,error_type,error_code
0,20260916_123809_00000_3jarb,FINISHED,trino-client,trino-python-client,SELECT version(),[global],4,28,79,2026-09-16 12:38:09.164000+00:00,2026-09-16 12:38:09.195000+00:00,2026-09-16 12:38:09.420000+00:00,2026-09-16 12:38:09.408000+00:00,None,None
1,20260916_123827_00001_3jarb,RUNNING,trino-client,trino-python-client,SELECT * FROM system.runtime.queries,[global],0,9,12,2026-09-16 12:38:27.654000+00:00,2026-09-16 12:38:27.663000+00:00,2026-09-16 12:38:27.688000+00:00,NaT,None,None

In [7]:
%%tsql
SELECT *
FROM iceberg.system.iceberg_tables

Empty DataFrame
Columns: [table_schema, table_name]
Index: []

In [8]:
%%tsql
SELECT table_catalog, table_schema, table_name, table_type
FROM iceberg.information_schema.tables
ORDER BY table_schema, table_name

  table_catalog        table_schema        table_name  table_type
0       iceberg  information_schema  applicable_roles  BASE TABLE
1       iceberg  information_schema           columns  BASE TABLE
2       iceberg  information_schema     enabled_roles  BASE TABLE
3       iceberg  information_schema             roles  BASE TABLE
4       iceberg  information_schema          schemata  BASE TABLE
5       iceberg  information_schema  table_privileges  BASE TABLE
6       iceberg  information_schema            tables  BASE TABLE
7       iceberg  information_schema             views  BASE TABLE
8       iceberg              system    iceberg_tables  BASE TABLE