In [1]:
%run_nb squid

In [1]:
%%tsql
SHOW CATALOGS;

SELECT table_catalog, table_schema, table_name, table_type
FROM iceberg.information_schema.tables
ORDER BY table_schema, table_name;

   Catalog
0    delta
1  iceberg
2   system

,table_catalog,table_schema,table_name,table_type
0,iceberg,information_schema,applicable_roles,BASE TABLE
1,iceberg,information_schema,columns,BASE TABLE
2,iceberg,information_schema,enabled_roles,BASE TABLE
3,iceberg,information_schema,roles,BASE TABLE
4,iceberg,information_schema,schemata,BASE TABLE
5,iceberg,information_schema,table_privileges,BASE TABLE
6,iceberg,information_schema,tables,BASE TABLE
7,iceberg,information_schema,views,BASE TABLE
8,iceberg,nyc_gov,country_codes,BASE TABLE
9,iceberg,nyc_gov,given_name_frequency,BASE TABLE
10,iceberg,nyc_gov,name_equivalence,BASE TABLE
11,iceberg,nyc_gov,popular_names_by_country_2026,BASE TABLE
12,iceberg,nyc_gov,surname_frequency,BASE TABLE
13,iceberg,system,iceberg_tables,BASE TABLE
14,iceberg,test,my_table,BASE TABLE

In [8]:
%%tsql
SELECT catalog_name, connector_name
FROM system.metadata.catalogs
ORDER BY catalog_name;

  catalog_name connector_name
0        delta     delta_lake
1      iceberg        iceberg
2       system         system

In [9]:
%tsql SHOW SCHEMAS FROM iceberg;

               Schema
0             default
1  information_schema
2             nyc_gov
3              system
4                test

In [29]:
%tsql  --max-colwidth 200 SHOW CREATE SCHEMA iceberg.nyc_gov;

                                                                                                                   Create Schema
0  CREATE SCHEMA iceberg.nyc_gov\nAUTHORIZATION USER "trino-client"\nWITH (\n   location = 's3a://trino-lakehouse/nyc_gov.db'\n)

In [7]:
%%tsql 
SHOW CREATE SCHEMA iceberg.nyc_gov;

                                       Create Schema
0  CREATE SCHEMA iceberg.nyc_gov\nAUTHORIZATION U...

In [10]:
%%tsql  
SHOW CREATE SCHEMA iceberg.nyc_gov;

                                       Create Schema
0  CREATE SCHEMA iceberg.nyc_gov\nAUTHORIZATION U...

In [14]:
%%tsql  --max-colwidth 200 
SHOW CREATE SCHEMA iceberg.nyc_gov;

                                                                                                                   Create Schema
0  CREATE SCHEMA iceberg.nyc_gov\nAUTHORIZATION USER "trino-client"\nWITH (\n   location = 's3a://trino-lakehouse/nyc_gov.db'\n)

In [13]:
%%tsql
SELECT *
FROM iceberg.nyc_gov.country_codes
LIMIT 4

     country_code country_name
0     Afghanistan           AF
1         Albania           AL
2         Algeria           DZ
3  American Samoa           AS