# Trino Catalogs

In [1]:
%%tsql
SELECT catalog_name, connector_name
FROM system.metadata.catalogs
ORDER BY catalog_name;

  catalog_name connector_name
0        delta     delta_lake
1      iceberg        iceberg
2       system         system

In [6]:
%tsql SHOW SCHEMAS FROM system;

               Schema
0  information_schema
1                jdbc
2            metadata
3             runtime

In [8]:
%tsql SHOW TABLES FROM system.metadata;

                           Table
0             analyze_properties
1                       catalogs
2              column_properties
3        functions_authorization
4   materialized_view_properties
5             materialized_views
6              schema_properties
7          schemas_authorization
8                 table_comments
9               table_properties
10          tables_authorization

In [9]:
%%tsql
SELECT *
FROM system.metadata.catalogs
ORDER BY catalog_name;

  catalog_name connector_id connector_name        state
0        delta        delta     delta_lake  OPERATIONAL
1      iceberg      iceberg        iceberg  OPERATIONAL
2       system       system         system  OPERATIONAL

In [11]:
%tsql SHOW SCHEMAS FROM delta;

               Schema
0             default
1  information_schema
2             nyc_gov
3                test

In [12]:
%tsql  --max-colwidth 200 SHOW CREATE SCHEMA delta.nyc_gov;

                                                                              Create Schema
0  CREATE SCHEMA delta.nyc_gov\nWITH (\n   location = 's3a://trino-lakehouse/nyc_gov.db'\n)